apiVersion: example.emailsender.yusuf/v1
kind: EmailSenderConfig
metadata:
  name: mailersend-senderconfig
spec:
  apiTokenSecretRef: "mailersend-secret"
  senderEmail: "yusuf@trial-3z0vklozx2e47qrx.mlsender.net" # Your sender email
  provider: "MailerSend"