# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: email-operator
    app.kubernetes.io/name: email-operator
    app.kubernetes.io/managed-by: kustomize
  name: email-operator-metrics-monitor
  namespace: system
spec:
  endpoints:
    - path: /metrics
      port: http # Ensure this is the name of the port that exposes HTTP metrics
      scheme: http
  selector:
    matchLabels:
      control-plane: email-operator
